spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ra
    url: jdbc:h2:mem:testdb
    username: ra
  jpa:
    properties:
      hibernate:
        show_sql: true
mail:
    host: smtp.gmail.com
    port: 587
    username: pratikpurbuj18@gmail.com
    password: Pratik@0909
    properties:
      mail:
         smtp:
            starttls:
              enable: true
            auth : true
    
    
